version: '2'
services:
    nginx:
        container_name: app-webserver
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - php-fpm
    php-fpm:
        container_name: app-php
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
    php-cli:
        container_name: app-php-cli
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        tty: true
    mysql:
        image: mysql:5.7
        container_name: app-mysql
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "33061:3306"
    node:
        container_name: app-frontend
        build: ./docker/node
        volumes:
                - ./:/var/www
        working_dir: /var/www
        tty: true
    php-test:
        container_name: app-php-test
        build:
            context: ./
            dockerfile: docker/php-test.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
